### ISSUE TITLE
It is not compatible with cancancan 3.0.1

### ISSUE THREAD

**Issue by taylancapraz** [CanCanCommunity/cancancan-mongoid#10]
How can I use cancancan-mongoid in a rails project with cancancan 3.0.1.
This forces me to downgrade the cancancan version.

> Bundler could not find compatible versions for gem "cancancan":
>   In snapshot (Gemfile.lock):
>     cancancan (= 3.0.1)
> 
>   In Gemfile:
>     cancancan
> 
>     cancancan-mongoid was resolved to 2.0.0.beta1, which depends on
>       cancancan (~> 2.0)

**Comment by coorasse** [comment]
PR are welcome! 👍

**Comment by rubydev** [comment]
Could you please merge this PR https://github.com/CanCanCommunity/cancancan-mongoid/pull/11 ?
