### ISSUE TITLE
I use mongoid, but raised unintialized ActiveRecod

### ISSUE THREAD

**Issue by lukefan** [CanCanCommunity/cancancan-mongoid#15]
uninitialized constant CanCan::Ability::ActiveRecord Did you mean? ActiveModel

![截屏2020-12-26 下午11 06 15](https://user-images.githubusercontent.com/3324749/103153888-f8ec4180-47ce-11eb-8b08-5efbba13ee1f.png)
 My Gemfile:

     ruby '2.7.0'
     gem 'mongoid', '~> 7.2.0'
     gem 'devise', '~> 4.7.3'
     gem 'graphql', '~> 1.11.6'
     gem 'rails_admin', '~> 2.0.2'
     gem 'cancancan', '~>3.2.0'
     gem 'cancancan-mongoid'
     gem 'rails', '~> 6.0.3', '>= 6.0.3.4'

My Ability.rb:

      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :rails_admin
        can :read, :dashboard
      else
        can :read, :all
      end

My config/initializers/rails_admin.rb

     ## == Devise ==
     config.authenticate_with do
         warden.authenticate! scope: :member
     end
     config.current_user_method(&:current_member)
     
     ## == CancanCan ==
     config.authorize_with :cancancan

I tried to open http://localhost:3000/admin, then redirect to sign_in. 
After sign in, I got this Error.

**Comment by coorasse** [comment]
This is fixed with cancancan 3.2.1. Please re-open if you have other issues.
