### ISSUE TITLE
Sqllite as development dependency.

### ISSUE THREAD

**Issue by shaunakpp** [CanCanCommunity/cancancan-mongoid#2]
Hello, 
I'm using this adapter for a personal project and had to modify the adapter a bit, but while installing the build I noticed that the .gemspec file mentions `sqllite` as a dependency. Since this is a Mongoid adapter is there a particular reason it is required?

**Comment by coorasse** [comment]
No. You can drop it. I's probably a wrong copy-paste. Thank you!
